name: vloc
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
assets:

fonts:
  - family : NunitoSans
    fonts:
      - asset: assets/fonts/NunitoSans-Regular.ttf
      - asset: assets/fonts/NunitoSans-SemiBold.ttf
        weight: 500
      - asset: assets/fonts/NunitoSans-Black.ttf
      - asset: assets/fonts/NunitoSans-BlackItalic.ttf
        style: italic
      - asset: assets/fonts/NunitoSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/NunitoSans-BoldItalic.ttf
        weight: 800
        style: italic  
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
